### ISSUE TITLE
Conflict with Cheat mod.

### ISSUE THREAD

**Issue by JoewAlabel** [benjaminfoo/Architect#10]
Could you make it compatible with Cheat mod, please?

After activating Architect we can't use no one command from Cheat mod.
Don't matter the priority order of loads of the mods.
Tested with no others mods than Architect and Cheat. Both on the latest version with latest steam kdc version: 1.9.6

I also tried to fix loading the cheat's files inside architect, but it won't worked =(
So I really appreciate if you can make both compatible, please ;)
This is the only sad reason I isn't using architect.

**Comment by benjaminfoo** [comment]
The latest version fixes this issue :-) !
