### ISSUE TITLE
Uninstallation reports entities still exist

### ISSUE THREAD

**Issue by ghost** [benjaminfoo/Architect#9]
I ran the #deleteall() function before uninstalling, however attempting to load up results in this error (crashing the game to desktop).

I assume the cleanup isn't occurring as required. Is there any additional information I can grab for you?
![image](https://user-images.githubusercontent.com/5128869/98670992-b0580080-23a7-11eb-9d5f-39397fe4288f.png)

**Comment by benjaminfoo** [comment]
Hey firesparq, thanks for using this github issues page - I currently dont have the time to work on this project anymore so there isnt a lot I can do for you - #deleteall should remove anything related to these entities. However, some newly introduced entities arent listed within the function. 

You can take a look at here: https://github.com/benjaminfoo/Architect/blob/2fd05d96d05902d7f0e9b9749f9975188085710c/Data/Scripts/Controller/arc_ConstructionController.lua

You could try the following:

- Open the console.
- Enter # and paste the following after the hashsign:

classesWhiteList = {
    "BasicBuildingEntity",
    "BathEntity",
    "BedEntity",
    "ChairEntity",
    "ChestEntity",
    "CookingSpotEntity",
    "DynamicBuildingEntity",
    "ECSManager",
    "GeneratorEntity",
    -- no we dont want to remove the previewEntity -- "PreviewEntity",
    "CustomShootingTarget",
    "TownBookEntity",
    "UIManager",
    "LadderEntity",
    "CookingSpotEntity"
}

- then call #deleteAll again - with the lines i wrote you re-setup the classes of entities which are going to get deleted (a class is for example CookingSpotEntity). If the error occurs again, but with a different entity, simply add it to the list (like i have) and rerun the #deleteAll function again - sorry for the inconvinience..

Maybe https://github.com/ChristianArvai @ChristianArvai has some fix for this as he provided good work on the modification.

**Comment by ghost** [comment]
Ok, it doesn't seem like that did anything for the problem. I guess I'll have to wait on Christian's potential response for a solution. Thanks for reaching out.

**Comment by ghost** [comment]
Just as an update, the reason I was wanting to uninstall was because of a modding conflict. For future reference, whilst it's not a perfect work around, I've found that modifying the .pak to just include the entity files and removing the rest worked.

That way, the script files don't conflict with any other mods, and the save is still able to reference the entity definitions.
